export const FALLBACK_COLLEGES = [
    // National Institutes
    {
        id: 'nitc',
        name: 'National Institute of Technology Calicut',
        slug: 'nitc',
        city: 'Kozhikode',
        state: 'Kerala',
    },
    {
        id: 'erdci',
        name: 'ER&DCI Institute of Technology, Trivandrum',
        slug: 'erdci',
        city: 'Trivandrum',
        state: 'Kerala',
    },
    {
        id: 'nielit',
        name: 'National Institute of Electronics & Information Technology, Calicut',
        slug: 'nielit',
        city: 'Kozhikode',
        state: 'Kerala',
    },
    {
        id: 'iist',
        name: 'Indian Institute of Space Science and Technology, Trivandrum',
        slug: 'iist',
        city: 'Trivandrum',
        state: 'Kerala',
    },
    {
        id: 'iiitk',
        name: 'Indian Institute of Information Technology Kottayam',
        slug: 'iiitk',
        city: 'Kottayam',
        state: 'Kerala',
    },
    {
        id: 'iit-pkd',
        name: 'Indian Institute of Technology Palakkad',
        slug: 'iit-pkd',
        city: 'Palakkad',
        state: 'Kerala',
    },
    {
        id: 'iiser-tvm',
        name: 'Indian Institute of Science Education and Research, Thiruvananthapuram',
        slug: 'iiser-tvm',
        city: 'Trivandrum',
        state: 'Kerala',
    },
    {
        id: 'sctimst',
        name: 'Sree Chitra Tirunal Institute for Medical Sciences and Technology',
        slug: 'sctimst',
        city: 'Trivandrum',
        state: 'Kerala',
    },

    // State Government Engineering Colleges
    {
        id: 'cet',
        name: 'College of Engineering, Trivandrum',
        slug: 'cet',
        city: 'Trivandrum',
        state: 'Kerala',
    },
    {
        id: 'gect',
        name: 'Government Engineering College, Thrissur',
        slug: 'gect',
        city: 'Thrissur',
        state: 'Kerala',
    },
    {
        id: 'tkmce',
        name: 'Thangal Kunju Musaliar College of Engineering',
        slug: 'tkmce',
        city: 'Kollam',
        state: 'Kerala',
    },
    {
        id: 'nssce',
        name: 'NSS College of Engineering',
        slug: 'nssce',
        city: 'Palakkad',
        state: 'Kerala',
    },
    {
        id: 'mace',
        name: 'Mar Athanasius College of Engineering',
        slug: 'mace',
        city: 'Kothamangalam',
        state: 'Kerala',
    },
    {
        id: 'gcek',
        name: 'Government College of Engineering, Kannur',
        slug: 'gcek',
        city: 'Kannur',
        state: 'Kerala',
    },
    {
        id: 'rit',
        name: 'Rajiv Gandhi Institute of Technology',
        slug: 'rit',
        city: 'Kottayam',
        state: 'Kerala',
    },
    {
        id: 'gecskp',
        name: 'Government Engineering College, Sreekrishnapuram',
        slug: 'gecskp',
        city: 'Palakkad',
        state: 'Kerala',
    },
    {
        id: 'gecb',
        name: 'Government Engineering College, Trivandrum (Barton Hill)',
        slug: 'gecb',
        city: 'Trivandrum',
        state: 'Kerala',
    },
    {
        id: 'geck',
        name: 'Government Engineering College, Kozhikode',
        slug: 'geck',
        city: 'Kozhikode',
        state: 'Kerala',
    },
    {
        id: 'gecw',
        name: 'Government Engineering College, Wayanad',
        slug: 'gecw',
        city: 'Wayanad',
        state: 'Kerala',
    },
    {
        id: 'geci',
        name: 'Government Engineering College, Idukki',
        slug: 'geci',
        city: 'Idukki',
        state: 'Kerala',
    },

    // Government Departments
    {
        id: 'mec',
        name: 'Government Model Engineering College',
        slug: 'mec',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'cec',
        name: 'College of Engineering Chengannur',
        slug: 'cec',
        city: 'Chengannur',
        state: 'Kerala',
    },
    {
        id: 'lbsce',
        name: 'L.B.S College of Engineering',
        slug: 'lbsce',
        city: 'Kasaragod',
        state: 'Kerala',
    },
    {
        id: 'lbsitw',
        name: 'L B S Institute of Technology for Women',
        slug: 'lbsitw',
        city: 'Trivandrum',
        state: 'Kerala',
    },
    {
        id: 'ceal',
        name: 'College of Engineering Attingal',
        slug: 'ceal',
        city: 'Attingal',
        state: 'Kerala',
    },
    {
        id: 'cectl',
        name: 'College of Engineering, Cherthala',
        slug: 'cectl',
        city: 'Cherthala',
        state: 'Kerala',
    },
    {
        id: 'cekpr',
        name: 'College of Engineering, Kallooppara',
        slug: 'cekpr',
        city: 'Kallooppara',
        state: 'Kerala',
    },
    {
        id: 'cek',
        name: 'College of Engineering, Karunagappally',
        slug: 'cek',
        city: 'Karunagappally',
        state: 'Kerala',
    },
    {
        id: 'cekra',
        name: 'College of Engineering, Kottarakkara',
        slug: 'cekra',
        city: 'Kottarakkara',
        state: 'Kerala',
    },
    {
        id: 'cep',
        name: 'College of Engineering, Poonjar',
        slug: 'cep',
        city: 'Poonjar',
        state: 'Kerala',
    },
    {
        id: 'aec',
        name: 'College of Engineering, Aranmula',
        slug: 'aec',
        city: 'Aranmula',
        state: 'Kerala',
    },
    {
        id: 'cekgr',
        name: 'College of Engineering, Kidangoor',
        slug: 'cekgr',
        city: 'Kidangoor',
        state: 'Kerala',
    },
    {
        id: 'cemp',
        name: 'College of Engineering & Management, Punnapra',
        slug: 'cemp',
        city: 'Punnapra',
        state: 'Kerala',
    },
    {
        id: 'pec',
        name: 'College of Engineering, Pathanapuram',
        slug: 'pec',
        city: 'Pathanapuram',
        state: 'Kerala',
    },
    {
        id: 'prn',
        name: 'College of Engineering, Perumon',
        slug: 'prn',
        city: 'Perumon',
        state: 'Kerala',
    },
    {
        id: 'tly',
        name: 'College of Engineering, Thalassery',
        slug: 'tly',
        city: 'Thalassery',
        state: 'Kerala',
    },
    {
        id: 'tkr',
        name: 'College of Engineering, Thrikaripur',
        slug: 'tkr',
        city: 'Trikaripur',
        state: 'Kerala',
    },
    {
        id: 'cev',
        name: 'College of Engineering, Vatakara',
        slug: 'cev',
        city: 'Vatakara',
        state: 'Kerala',
    },
    {
        id: 'cem',
        name: 'College of Engineering Muttathara',
        slug: 'cem',
        city: 'Muttathara',
        state: 'Kerala',
    },
    {
        id: 'mnr',
        name: 'College of Engineering Munnar',
        slug: 'mnr',
        city: 'Munnar',
        state: 'Kerala',
    },
    {
        id: 'cea',
        name: 'College of Engineering, Adoor',
        slug: 'cea',
        city: 'Adoor',
        state: 'Kerala',
    },
    {
        id: 'sctce',
        name: 'Sree Chitra Thirunal College of Engineering',
        slug: 'sctce',
        city: 'Trivandrum',
        state: 'Kerala',
    },

    // Universities
    {
        id: 'cusat',
        name: 'School of Engineering, CUSAT',
        slug: 'cusat',
        city: 'Kochi',
        state: 'Kerala',
    },
    {
        id: 'cucek',
        name: 'Cochin University College of Engineering Kuttanad',
        slug: 'cucek',
        city: 'Alappuzha',
        state: 'Kerala',
    },
    {
        id: 'cuiet',
        name: 'Calicut University Institute of Engineering & Technology',
        slug: 'cuiet',
        city: 'Tenhipalam',
        state: 'Kerala',
    },
    {
        id: 'ucek',
        name: 'University College of Engineering, Kariavattom',
        slug: 'ucek',
        city: 'Trivandrum',
        state: 'Kerala',
    },
    {
        id: 'uce',
        name: 'University College of Engineering, Thodupuzha',
        slug: 'uce',
        city: 'Thodupuzha',
        state: 'Kerala',
    },
    {
        id: 'kcaet',
        name: 'Kelappaji College of Agricultural Engineering and Technology',
        slug: 'kcaet',
        city: 'Tavanur',
        state: 'Kerala',
    },

    // Private Self-Financing
    {
        id: 'ace',
        name: 'ACE College of Engineering',
        slug: 'ace',
        city: 'Trivandrum',
        state: 'Kerala',
    },
    {
        id: 'asi',
        name: 'Adi Shankara Institute of Engineering Technology',
        slug: 'asi',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'atp',
        name: 'Ahalia School of Engineering and Technology',
        slug: 'atp',
        city: 'Palakkad',
        state: 'Kerala',
    },
    {
        id: 'aae',
        name: 'Al Azhar College of Engineering and Technology',
        slug: 'aae',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'aap',
        name: 'Al-Ameen Engineering College',
        slug: 'aap',
        city: 'Palakkad',
        state: 'Kerala',
    },
    {
        id: 'aik',
        name: 'Albertian Institute of Science and Technology',
        slug: 'aik',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'ajc',
        name: 'Amal Jyothi College of Engineering',
        slug: 'ajc',
        city: 'Kottayam',
        state: 'Kerala',
    },
    {
        id: 'ame',
        name: 'Ammini College of Engineering',
        slug: 'ame',
        city: 'Palakkad',
        state: 'Kerala',
    },
    {
        id: 'awh',
        name: 'AWH Engineering College',
        slug: 'awh',
        city: 'Kozhikode',
        state: 'Kerala',
    },
    {
        id: 'axe',
        name: 'Axis College of Engineering and Technology',
        slug: 'axe',
        city: 'Thrissur',
        state: 'Kerala',
    },
    {
        id: 'bmc',
        name: 'Baselios Mathews II College of Engineering',
        slug: 'bmc',
        city: 'Kollam',
        state: 'Kerala',
    },
    {
        id: 'bte',
        name: 'Baselios Thomas I Catholicose College of Engineering',
        slug: 'bte',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'cml',
        name: 'Believers Church Caarmel Engineering College',
        slug: 'cml',
        city: 'Pathanamthitta',
        state: 'Kerala',
    },
    {
        id: 'bjk',
        name: 'Bishop Jerome Institute',
        slug: 'bjk',
        city: 'Kollam',
        state: 'Kerala',
    },
    {
        id: 'cma',
        name: 'Carmel College of Engineering and Technology',
        slug: 'cma',
        city: 'Alappuzha',
        state: 'Kerala',
    },
    {
        id: 'cce',
        name: 'Christ College of Engineering',
        slug: 'cce',
        city: 'Thrissur',
        state: 'Kerala',
    },
    {
        id: 'ckc',
        name: 'Christ Knowledge City',
        slug: 'ckc',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'ccv',
        name: 'Cochin College of Engineering and Technology',
        slug: 'ccv',
        city: 'Malappuram',
        state: 'Kerala',
    },
    {
        id: 'cim',
        name: 'Cochin Institute of Science and Technology',
        slug: 'cim',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'cen',
        name: 'College of Engineering and Technology, Payyanur',
        slug: 'cen',
        city: 'Kannur',
        state: 'Kerala',
    },
    {
        id: 'ekc',
        name: 'Eranad Knowledge City Technical Campus',
        slug: 'ekc',
        city: 'Malappuram',
        state: 'Kerala',
    },
    {
        id: 'fit',
        name: 'Federal Institute of Science and Technology',
        slug: 'fit',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'git',
        name: 'Gurudeva Institute of Science And Technology',
        slug: 'git',
        city: 'Kottayam',
        state: 'Kerala',
    },
    {
        id: 'hce',
        name: 'Heera College of Engineering and Technology',
        slug: 'hce',
        city: 'Trivandrum',
        state: 'Kerala',
    },
    {
        id: 'hgw',
        name: 'Holy Grace Academy of Engineering',
        slug: 'hgw',
        city: 'Thrissur',
        state: 'Kerala',
    },
    {
        id: 'hkc',
        name: 'MGM College of Engineering & Technology',
        slug: 'hkc',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'ies',
        name: 'IES College of Engineering',
        slug: 'ies',
        city: 'Thrissur',
        state: 'Kerala',
    },
    {
        id: 'ice',
        name: 'Ilahia College of Engineering Technology',
        slug: 'ice',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'ict',
        name: 'Ilahia School of Science and Technology',
        slug: 'ict',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'igw',
        name: 'Indira Gandhi Institute of Engineering and Technology For Women',
        slug: 'igw',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'jbt',
        name: 'Jai Bharath College of Management and Engineering Technology',
        slug: 'jbt',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'jce',
        name: 'Jawaharlal College of Engineering and Technology',
        slug: 'jce',
        city: 'Palakkad',
        state: 'Kerala',
    },
    {
        id: 'jit',
        name: 'John Cox Memorial C S I Institute of Technology',
        slug: 'jit',
        city: 'Trivandrum',
        state: 'Kerala',
    },
    {
        id: 'jec',
        name: 'Jyothi Engineering College',
        slug: 'jec',
        city: 'Thrissur',
        state: 'Kerala',
    },
    {
        id: 'kme',
        name: 'K M E A Engineering College',
        slug: 'kme',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'kmc',
        name: 'KMCT College of Engineering',
        slug: 'kmc',
        city: 'Kozhikode',
        state: 'Kerala',
    },
    {
        id: 'kmw',
        name: 'KMCT College of Engineering For Women',
        slug: 'kmw',
        city: 'Kozhikode',
        state: 'Kerala',
    },
    {
        id: 'kit',
        name: 'Kottayam Institute of Technology and Science',
        slug: 'kit',
        city: 'Kottayam',
        state: 'Kerala',
    },
    {
        id: 'lmc',
        name: 'Lourdes Matha College of Science and Technology',
        slug: 'lmc',
        city: 'Trivandrum',
        state: 'Kerala',
    },
    {
        id: 'mea',
        name: 'MEA Engineering College',
        slug: 'mea',
        city: 'Malappuram',
        state: 'Kerala',
    },
    {
        id: 'mes',
        name: 'MES College of Engineering',
        slug: 'mes',
        city: 'Malappuram',
        state: 'Kerala',
    },
    {
        id: 'mgc',
        name: 'M G College of Engineering',
        slug: 'mgc',
        city: 'Trivandrum',
        state: 'Kerala',
    },
    {
        id: 'dmc',
        name: 'M. Dasan Institute of Technology',
        slug: 'dmc',
        city: 'Kozhikode',
        state: 'Kerala',
    },
    {
        id: 'mcet-malabar',
        name: 'Malabar College of Engineering and Technology',
        slug: 'mcet-malabar',
        city: 'Thrissur',
        state: 'Kerala',
    },
    {
        id: 'mlt',
        name: 'Malabar Institute of Technology',
        slug: 'mlt',
        city: 'Kannur',
        state: 'Kerala',
    },
    {
        id: 'mlm',
        name: 'Mangalam College of Engineering',
        slug: 'mlm',
        city: 'Kottayam',
        state: 'Kerala',
    },
    {
        id: 'mbc',
        name: 'Mar Baselios Christian College of Engineering and Technology',
        slug: 'mbc',
        city: 'Idukki',
        state: 'Kerala',
    },
    {
        id: 'mbt',
        name: 'Mar Baselios College of Engineering and Technology',
        slug: 'mbt',
        city: 'Trivandrum',
        state: 'Kerala',
    },
    {
        id: 'mbi',
        name: 'Mar Baselios Institute of Technology and Science',
        slug: 'mbi',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'mee',
        name: 'MES College of Engineering and Technology',
        slug: 'mee',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'mek',
        name: 'MES Institute of Technology and Management',
        slug: 'mek',
        city: 'Kollam',
        state: 'Kerala',
    },
    {
        id: 'met',
        name: "MET'S School of Engineering",
        slug: 'met',
        city: 'Thrissur',
        state: 'Kerala',
    },
    {
        id: 'mct',
        name: 'Mohandas College of Engineering and Technology',
        slug: 'mct',
        city: 'Trivandrum',
        state: 'Kerala',
    },
    {
        id: 'mzc',
        name: 'Mount Zion College of Engineering',
        slug: 'mzc',
        city: 'Pathanamthitta',
        state: 'Kerala',
    },
    {
        id: 'mzw',
        name: 'Mount Zion College of Engineering For Women',
        slug: 'mzw',
        city: 'Alappuzha',
        state: 'Kerala',
    },
    {
        id: 'mcc',
        name: 'Musaliar College of Engineering',
        slug: 'mcc',
        city: 'Trivandrum',
        state: 'Kerala',
    },
    {
        id: 'mck',
        name: 'Musaliar College of Engineering and Technology',
        slug: 'mck',
        city: 'Pathanamthitta',
        state: 'Kerala',
    },
    {
        id: 'mus',
        name: 'Muslim Association College of Engineering',
        slug: 'mus',
        city: 'Trivandrum',
        state: 'Kerala',
    },
    {
        id: 'mut',
        name: 'Muthoot Institute of Technology and Science',
        slug: 'mut',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'nce',
        name: 'Nehru College of Engineering and Research Centre',
        slug: 'nce',
        city: 'Thrissur',
        state: 'Kerala',
    },
    {
        id: 'nie',
        name: 'Nirmala College of Engineering',
        slug: 'nie',
        city: 'Thrissur',
        state: 'Kerala',
    },
    {
        id: 'prc',
        name: 'Providence College of Engineering',
        slug: 'prc',
        city: 'Alappuzha',
        state: 'Kerala',
    },
    {
        id: 'rie',
        name: 'Rajadhani Institute of Engineering and Technology',
        slug: 'rie',
        city: 'Trivandrum',
        state: 'Kerala',
    },
    {
        id: 'ret',
        name: 'Rajagiri School of Engineering and Technology',
        slug: 'ret',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'rce',
        name: 'Royal College of Engineering and Technology',
        slug: 'rce',
        city: 'Thrissur',
        state: 'Kerala',
    },
    {
        id: 'shr',
        name: 'Sahrdaya College of Engineering and Technology',
        slug: 'shr',
        city: 'Thrissur',
        state: 'Kerala',
    },
    {
        id: 'mgp',
        name: 'Saintgits College of Engineering',
        slug: 'mgp',
        city: 'Kottayam',
        state: 'Kerala',
    },
    {
        id: 'sit',
        name: 'Sarabhai Institute of Science and Technology',
        slug: 'sit',
        city: 'Trivandrum',
        state: 'Kerala',
    },
    {
        id: 'scm',
        name: 'SCMS School of Engineering and Technology',
        slug: 'scm',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'snm',
        name: 'SNM Institute of Management and Technology',
        slug: 'snm',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'sbc',
        name: 'Sree Buddha College of Engineering',
        slug: 'sbc',
        city: 'Alappuzha',
        state: 'Kerala',
    },
    {
        id: 'sbw',
        name: 'Sree Buddha College of Engineering For Women',
        slug: 'sbw',
        city: 'Pathanamthitta',
        state: 'Kerala',
    },
    {
        id: 'snc',
        name: 'Sree Narayana Guru College of Engineering and Technology',
        slug: 'snc',
        city: 'Kannur',
        state: 'Kerala',
    },
    {
        id: 'snt',
        name: 'Sree Narayana Guru Institute of Science and Technology',
        slug: 'snt',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'sng',
        name: 'Sree Narayana Gurukulam College of Engineering',
        slug: 'sng',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'snp',
        name: 'Sree Narayana Institute of Technology',
        slug: 'snp',
        city: 'Pathanamthitta',
        state: 'Kerala',
    },
    {
        id: 'spt',
        name: 'Sreepathy Institute of Management and Technology',
        slug: 'spt',
        city: 'Palakkad',
        state: 'Kerala',
    },
    {
        id: 'vpe',
        name: 'Sri Vellappally Natesan College of Engineering',
        slug: 'vpe',
        city: 'Alappuzha',
        state: 'Kerala',
    },
    {
        id: 'sjc',
        name: "St. Joseph's College of Engineering and Technology",
        slug: 'sjc',
        city: 'Kottayam',
        state: 'Kerala',
    },
    {
        id: 'stm',
        name: 'St. Thomas College of Engineering and Technology, Sivapuram',
        slug: 'stm',
        city: 'Kannur',
        state: 'Kerala',
    },
    {
        id: 'stc',
        name: 'St. Thomas College of Engineering and Technology, Chengannur',
        slug: 'stc',
        city: 'Alappuzha',
        state: 'Kerala',
    },
    {
        id: 'sti',
        name: 'St.Thomas Institute for Science and Technology',
        slug: 'sti',
        city: 'Trivandrum',
        state: 'Kerala',
    },
    {
        id: 'tki',
        name: 'TKM Institute of Technology',
        slug: 'tki',
        city: 'Kollam',
        state: 'Kerala',
    },
    {
        id: 'tje',
        name: 'Thejus Engineering College',
        slug: 'tje',
        city: 'Thrissur',
        state: 'Kerala',
    },
    {
        id: 'toc',
        name: 'Toc H Institute of Science and Technology',
        slug: 'toc',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'tce',
        name: 'Toms College of Engineering For Startups',
        slug: 'tce',
        city: 'Kottayam',
        state: 'Kerala',
    },
    {
        id: 'tct',
        name: 'Trinity College of Engineering',
        slug: 'tct',
        city: 'Thiruvananthapuram',
        state: 'Kerala',
    },
    {
        id: 'ukp',
        name: 'UKF College of Engineering and Technology',
        slug: 'ukp',
        city: 'Kollam',
        state: 'Kerala',
    },
    {
        id: 'unt',
        name: 'Universal Engineering College',
        slug: 'unt',
        city: 'Thrissur',
        state: 'Kerala',
    },
    {
        id: 'vke',
        name: 'Valia Koonambaikulathamma College of Engineering and Technology',
        slug: 'vke',
        city: 'Kollam',
        state: 'Kerala',
    },
    {
        id: 'vvt',
        name: 'Vedavyasa Institute of Technology',
        slug: 'vvt',
        city: 'Malappuram',
        state: 'Kerala',
    },
    {
        id: 'vas',
        name: 'Vidya Academy of Science and Technology',
        slug: 'vas',
        city: 'Thrissur',
        state: 'Kerala',
    },
    {
        id: 'vak',
        name: 'Vidya Academy of Science and Technology Technical Campus',
        slug: 'vak',
        city: 'Thiruvananthapuram',
        state: 'Kerala',
    },
    {
        id: 'vit',
        name: 'VISAT Engineering College',
        slug: 'vit',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'vml',
        name: 'Vimal Jyothi Engineering College',
        slug: 'vml',
        city: 'Kannur',
        state: 'Kerala',
    },
    {
        id: 'vjc',
        name: 'Viswajyothi College of Engineering and Technology',
        slug: 'vjc',
        city: 'Ernakulam',
        state: 'Kerala',
    },
    {
        id: 'ycw',
        name: 'Younus College of Engineering',
        slug: 'ycw',
        city: 'Kollam',
        state: 'Kerala',
    },
];
